# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  pathtosolution: 'EMS/'
  pathtoproject: 'EMS/EMS_Web'
  pathtotest: 'EMS/Test'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'EMSSonarServiceConnection'
    organization: '200106-uta-prs-net'
    scannerMode: 'MSBuild'
    projectKey: 'EMSPipelinetoken'
    projectName: 'EMS'
    extraProperties: ''

- script: 
    dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test
    --configuration $(buildConfiguration)
    --logger trx
    --no-build
    --results-directory $(Build.ArtifactStagingDirectory)/test/
    /p:CollectCoverage=true
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet test'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(pathtotest)'
    workingDirectory: '$(pathtosolution)'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'